Token metadata api
hubbleprotocol/hubble-public-api pull request #120
Opened 2022-09-28 10:51 UTC by elliotkennedy

Add a [Fungible token standard](https://docs.metaplex.com/programs/token-metadata/token-standard#the-fungible-standard) endpoint for kTokens.

Dynamic endpoint which validates the token mint passed is owned by Kamino.

Reads on-chain metadata to dynamically generate the full token metadata json object.

2022-09-28 11:38 UTC, peroxy requested changes

2022-09-28 11:38 UTC, peroxy commented on Dockerfile
> +RUN apk --no-cache -U upgrade
Any specific reason for this?

2022-09-28 11:38 UTC, peroxy commented on Dockerfile
> +ENV APP_VERSION ${APP_VERSION}
How come you renamed this to APP_VERSION? I don't see a good reason + I think you would have to rename the references in the code as well that use this (health+version endpoints)

2022-09-28 11:38 UTC, peroxy commented on src/api/kamino/ktoken-metadata.ts
> +        await sendWithCacheControl(getKTokenMetadataRedisKey(mint, env), response, KtokenLogo);
Nitpick: `getKTokenMetadataRedisKey(mint, env)` can be replaced with `key` variable

2022-09-28 11:38 UTC, peroxy commented on src/api/kamino/ktoken-metadata.ts
> +      if (metadata) {
If no metadata is found for a specific mint, this will throw an internal server error which isn't great for API clients. Ideally, the getKTokenMetadata method would log the issue and return null/undefined and you could produce 404 not found response instead. I'm open to other solutions as well, but the 500 error with message UnsupportedMint is a bit too vague.

The disadvantage I also see with this current setup is that the cache breaking would also be easy as it would fetch the onchain data everytime, instead of retreiving undefined/null value from the cache directly.

2022-09-28 11:43 UTC, peroxy commented on src/api/routes.ts
> +routesList.push({ endpoint: '/ktoken/metadata', route: kTokenMetadataRoute });
I would prefer having a route that's more RESTful (even though we don't have that perfect with all routes, I am aware :disappointed: ), so a plural + pubkey after the first resource:

 `/ktokens/:token_pubkey/metadata`
 and `/ktokens/:token_pubkey/image.svg`

2022-09-28 11:44 UTC, elliotkennedy commented on Dockerfile
> +ENV APP_VERSION ${APP_VERSION}
Reverted but I just wanted to rename because every other project uses APP_ so to keep the dockerfiles similiar

2022-09-28 11:45 UTC, peroxy commented on Dockerfile
> +ENV APP_VERSION ${APP_VERSION}
Ok, I see.. I am fine with the rename in that case, but I think you need to look for all references (I think version and health endpoint both use it) + change it in the helm charts.

2022-09-28 11:45 UTC, elliotkennedy commented on src/api/kamino/ktoken-metadata.ts
> +      if (metadata) {
This is why I want to add throttling + caching with varnish

2022-09-28 11:46 UTC, elliotkennedy commented on src/api/kamino/ktoken-metadata.ts
> +      if (metadata) {
Will add tonight or tomorrow

2022-09-28 11:48 UTC, elliotkennedy commented on src/api/routes.ts
> +routesList.push({ endpoint: '/ktoken/metadata', route: kTokenMetadataRoute });
I'm keen for consistency, I've just always done singular paths

Ok for reordering but the image is a child of the metadata imo

2022-09-28 11:50 UTC, elliotkennedy commented on Dockerfile
> +RUN apk --no-cache -U upgrade
I was done in another step previously - it will have the same effect just hit the cache more often this way

2022-09-28 11:50 UTC, peroxy commented on src/api/routes.ts
> +routesList.push({ endpoint: '/ktoken/metadata', route: kTokenMetadataRoute });
OK yeah, I agree with the metadata image part.

2022-09-28 11:50 UTC, elliotkennedy commented on Dockerfile
> +RUN apk --no-cache -U upgrade
I guess it made more sense in base to me :shrug:

2022-09-28 11:50 UTC, peroxy commented on Dockerfile
> +RUN apk --no-cache -U upgrade
Cool, thanks for explaining

2022-09-28 11:50 UTC, elliotkennedy commented on src/api/kamino/ktoken-metadata.ts
> +        await sendWithCacheControl(getKTokenMetadataRedisKey(mint, env), response, KtokenLogo);
Ooops

2022-09-28 15:38 UTC, peroxy commented
@elliotkennedy can you please also add sample requests for the new endpoints to the README?

2022-09-28 17:23 UTC, y2kappa approved these changes
lgtm, but will let @peroxy give the final approval

2022-10-05 18:12 UTC, elliotkennedy commented
> @elliotkennedy can you please also add sample requests for the new endpoints to the README?

Done

2022-10-05 18:12 UTC, elliotkennedy commented on src/api/kamino/ktoken-metadata.ts
> +      if (metadata) {
Testing caching on devnet currently

2022-10-05 18:13 UTC, elliotkennedy commented
Hey @peroxy - this is ready for another look please. Thanks

2022-10-05 18:15 UTC, peroxy approved these changes
LGTM, great work!

2022-10-05 18:16 UTC, merged