Feat/modify staking apr
hubbleprotocol/hubble-public-api pull request #90
Opened 2022-08-22 18:55 UTC by andreihrs

2022-08-22 18:56 UTC, andreihrs commented on src/api/staking.ts
> +    {
not sure if we want to expose in a different endpoint this

2022-08-22 19:10 UTC, peroxy requested changes

2022-08-22 19:10 UTC, peroxy commented on src/api/staking.ts
> +    {
I don’t think liquidation rewards are connected to staking to be honest. I would make a new endpoint for this, something like /stability/liquidation-rewards or just /liquidation-rewards

2022-08-23 08:46 UTC, peroxy approved these changes

2022-08-23 08:46 UTC, peroxy commented on src/api/stability.ts
> +  '/liquidation-rewards',
Please add this route to the README.md as well, so it is documented if anyone wants to use it

2022-08-23 09:02 UTC, merged